[package]
name = "tasque"
description = "A middleware for tower sessions"
version = "0.1.1"
edition = "2021"
rust-version = "1.75.0"
authors = ["Jimmie Lovell <jimmieomlovell@gmail.com>"]
license = "MIT"
homepage = "https://github.com/jimmielovell/tasque"
keywords = ["task", "scheduler", "watfoe"]
repository = "https://github.com/jimmielovell/tasque"
readme = "README.md"

[dependencies]
async-trait = "0.1.88"
rand = "0.9.1"
tokio = { version = "1.44.2", features = ["macros", "rt", "sync", "time"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[[example]]
name = "simple"
path = "examples/simple.rs"

[[test]]
name = "basic"
path = "tests/basic.rs"

[[test]]
name = "aging"
path = "tests/aging.rs"
